### ISSUE TITLE
Value for current in the experiences

### ISSUE THREAD

**Issue by artpdr** [sonhan/contiki#1]
Hi Son Han.
I've already tried to contact you via thingschat blog, without success yet.
Can you please provide me the page and datasheet from where you got the Current value (0.33) that you use to calculate the power consumed by the CPU? This value is for example in cell R4 of sheet "endnote" in file data-real-power.xslx. 
Thanks in advance.
Cheers.

**Comment by sonhan** [comment]
Hey, I used CM5000 mote here https://www.advanticsys.com/shop/mtmcm5000msp-p-14.html. You can find current and voltage in datasheet provided on the product page.

**Comment by artpdr** [comment]
I'm working exactly with the same device as you (MTM-CM5000MSP) and I can't find the value 0.33 in the datasheet. 
If you don't mind go to page 26 of the datasheet! I think you are mistakenly using 0.33 mA because this value is when your device use 2.2 V.
However, in your formulas you use 3 V batteries. So, instead of 0.33 mA I think that what is correct is 0.55 mA. 
Correct me if I'm wrong.
Cheers.

**Comment by sonhan** [comment]
Yeah, likely. Can you share the screenshot of the datasheet both here and on the blog post for anyone has the same issue

**Comment by artpdr** [comment]
![screenshot from 2017-09-07 01-26-45](https://user-images.githubusercontent.com/13767672/30140532-369add3a-936d-11e7-84c4-9ae0498371e9.png)

As we can see in the image above, when we use 3V (two batteries in the device), the cpu current is 500uA (green) = 0.5mA, not 0.33mA (red).
I haven't checked the other values that you calculated for lpm, tx and rx... If I find any strange value I will let you know.

**Comment by sonhan** [comment]
Thanks buddy!

**Comment by Tawbah** [comment]
hello artpdr  
can you please help me with the current values for lpm, tx and rx .
thank you in advance.
